# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cognition, Language and Computation Lab
description: >-
  The Cognition, Language and Computation lab lead by Jelle Zuidema 
  at the Institute for Logic, Language and Computation 
  at the University of Amsterdam.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://projects.illc.uva.nl/LaCo/clclab/"

# Build settings
destination: site
source: jekyll
encoding: utf-8
markdown: kramdown
exclude: 
  - node_modules

# Jekkyl Scholar 
# See here for a useful tutorial: 
# https://pages.lip6.fr/Pascal.Poizat/blog/posts/2016/02/01/jekyll-and-bibtex/
plugins: ['jekyll/scholar', 'jekyll-twitter-plugin']

scholar:
  style: apa-no-doi-no-issue
  sort_by: year
  order: descending
  bibliography: publications.bib
  bibliography_template: bib
  source: ./
  #bibtex_skip_fields: [mendeley-tags, file, url]
  bibtex_filters:
    - latex
    - markdown


